#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_F3B) += focaltech_flash/

