#
# Makefile for the fingerprint drivers.
#

subdir-ccflags-y := -finline-functions -ftree-vectorize -funroll-loops

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
